'use client'
import { useEffect, useState } from 'react'
import Dashboard from './Components/Dashboard'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { usePathname, useRouter } from 'next/navigation'
import { ToastContainer } from 'react-toastify'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">

      <body className={inter.className}>
        <ToastContainer
          position="top-center"
          theme="colored"
        />
        <Dashboard >
          {children}
        </Dashboard>
      </body>
    </html>
  )
}
